FROM adoptopenjdk/openjdk11



RUN apt-get update
RUN apt-get upgrade -y
# Upgrade installed packages
RUN apt update && apt upgrade -y && apt clean
RUN apt install python3.8 -y
RUN apt install python -y
RUN apt install pip -y


# container에 git 설치
RUN apt-get install git -y
RUN git clone https://github.com/twinson37/yolov5.git ./root/yolov5

RUN pip install -r ./root/yolov5/requirements.txt
RUN pip install DeepImageSearch --upgrade

RUN rm -rf ./root/yolov5

RUN apt-get install libgl1-mesa-glx -y
RUN apt-get install libglib2.0-0 -y